<script language="javascript" type="text/javascript" src="<?= MODULES_PUBLIC_DIR ?>/ppm/fileManager/tinymce/tiny_mce/tiny_mce.js"></script>
<script language="javascript" type="text/javascript">
    function myFileBrowser (field_name, url, type, win) {
        //alert("Field_Name: " + field_name + "\nURL: " + url + "\nType: " + type + "\nWin: " + win); // debug/testing

       /* If you work with sessions in PHP and your client doesnt accept cookies you might need to carry
        the session name and session ID in the request string (can look like this: "?PHPSESSID=88p0n70s9dsknra96qhuk6etm5").
        These lines of code extract the necessary parameters and add them back to the filebrowser URL again. */

        //var cmsURL = window.location.toString();    // script URL - use an absolute path!
        var cmsURL = "<?= MODULES_PUBLIC_DIR ?>/ppm/fileManager/";    // script URL - use an absolute path!

        if (cmsURL.indexOf("?") < 0) {
            //add the type as the only query parameter
            cmsURL = cmsURL + "?type=" + type;
        }
        else {
            //add the type as an additional query parameter
            // (PHP session ID is now included if there is one at all)
            cmsURL = cmsURL + "&type=" + type;
        }

        windowWidth = screen.width-Math.round(screen.width/10);
        windowHeight = screen.height-(2*Math.round(screen.height/10));

        tinyMCE.activeEditor.windowManager.open({
            file : cmsURL,
            title : "File Browser",
            width : windowWidth,  // Your dimensions may differ - toy around with them!
            height : windowHeight,
            resizable : "yes",
            scrollbars : "yes",
            inline : 1,  // This parameter only has an effect if you use the inlinepopups plugin!
            close_previous : "no"
        }, {
            window : win,
            input : field_name
        });
        return false;
    }


    tinyMCE.init({
        language : "ru",
        mode : "exact",
        elements : "blog_content",
        theme : "advanced",
        plugins : "advlink,table,save,paste,template,contextmenu,pagebreak,announce,inlinepopups,clearbr",
        extended_valid_elements : "announce",
        valid_elements : "announce",

        extended_valid_elements : "br[clear]",

//invalid_elements : "script,iframe,input,frame,style",
        invalid_elements : "script,input,frame,style",

        document_base_url : "http://{{ Env.server_name }}/",
        convert_urls : false,
        fix_nesting : true,

        verify_html : false,
        width : "100%",
        height : "500px",

// Example content CSS (should be your site CSS)
        theme_advanced_font_sizes: "10px,12px,13px,14px,16px,18px,20px",
        font_size_style_values : "10px,12px,13px,14px,16px,18px,20px",

        file_browser_callback : "myFileBrowser",

// full mode
        theme_advanced_buttons1 : "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,pagebreak,announce,|,code,clearbr",
        theme_advanced_buttons2 : "pastetext,pasteword,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,anchor,link,unlink,image,|,hr,removeformat,|,sub,sup,|,charmap",

// light mode
//theme_advanced_buttons1 : "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,|,announce,|,code",
//theme_advanced_buttons2 : "pastetext,pasteword,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,image,|,hr",
// simple mode
//theme_advanced_buttons1 : "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,code",
//theme_advanced_buttons2 : "undo,redo,|,anchor,link,unlink",

        theme_advanced_buttons3 : "",
// Разрешить таблицы
//theme_advanced_buttons3 : "tablecontrols",

        theme_advanced_toolbar_location : "top",
        theme_advanced_toolbar_align : "left",
        theme_advanced_statusbar_location : "bottom",
        theme_advanced_resizing : true,

        forced_root_block : "",
//forced_root_block : false,
        force_br_newlines : false,
        force_p_newlines : true,

        setup : function(ed) {
            ed.onInit.add(function(ed){
                //var content = ed.getContent();
                var content = document.getElementById("blog_content").value;
                tinyMCE.activeEditor.setContent(content);
            });
        }
    });

    function toggleEditor(id) {
        if (!tinyMCE.get(id))
            tinyMCE.execCommand("mceAddControl", false, id);
        else
            tinyMCE.execCommand("mceRemoveControl", false, id);
    }
</script>
